site_name: ATS 說明文件
site_url: https://bravotek1.github.io/ATS/
repo_url: https://github.com/Bravotek1/ATS

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

nav:
  - 首頁: index.md
  - 快速開始: quickstart.md
  - API 文件: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            # 顯示行為
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_root_toc_entry: true
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            members_order: source

            # ⬇️ 這幾個是關鍵：把原本被濾掉的也顯示出來
            inherited_members: true
            show_private_members: true
            show_submodules: true
            filters: []           # 取消 "!^_" 的預設過濾
            docstring_style: google

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
